Entity/Message.php
<?php

/*
 * This file is part of the CCDNMessage MessageBundle
 *
 * (c) CCDN (c) CodeConsortium <http://www.codeconsortium.com/>
 *
 * Available on github <http://www.github.com/codeconsortium/>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace CCDNMessage\MessageBundle\Entity;

use CCDNMessage\MessageBundle\Entity\Model\MessageModel;

/**
 *
 * @category CCDNMessage
 * @package  MessageBundle
 *
 * @author   Reece Fowell <reece@codeconsortium.com>
 * @license  http://opensource.org/licenses/MIT MIT
 * @version  Release: 2.0
 * @link     https://github.com/codeconsortium/CCDNMessageMessageBundle
 *
 */
class Message extends MessageModel
{
    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var string $sendTo
     */
    protected $sendTo;

    /**
     * @var string $name
     */
    protected $subject;

    /**
     * @var string $name
     */
    protected $body;

    /**
     * @var \DateTime $createdDate
     */
    protected $createdDate;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get sendTo
     *
     * @return text
     */
    public function getSendTo()
    {
        return $this->sendTo;
    }

    /**
     * Set sendTo
     *
     * @param  text    $sendTo
     * @return Message
     */
    public function setSendTo($sendTo)
    {
        $this->sendTo = $sendTo;

        return $this;
    }

    /**
     * Get subject
     *
     * @return string
     */
    public function getSubject()
    {
        return $this->subject;
    }

    /**
     * Set subject
     *
     * @param  string  $subject
     * @return Message
     */
    public function setSubject($subject)
    {
        $this->subject = $subject;

        return $this;
    }

    /**
     * Get body
     *
     * @return text
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Set body
     *
     * @param  text    $body
     * @return Message
     */
    public function setBody($body)
    {
        $this->body = $body;

        return $this;
    }

    /**
     * Get createdDate
     *
     * @return datetime
     */
    public function getCreatedDate()
    {
        return $this->createdDate;
    }

    /**
     * Set createdDate
     *
     * @param  datetime $createdDate
     * @return Message
     */
    public function setCreatedDate($createdDate)
    {
        $this->createdDate = $createdDate;

        return $this;
    }
}

Controller/BaseController.php
<?php

/*
 * This file is part of the CCDNMessage MessageBundle
 *
 * (c) CCDN (c) CodeConsortium <http://www.codeconsortium.com/>
 *
 * Available on github <http://www.github.com/codeconsortium/>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace CCDNMessage\MessageBundle\Controller;

use Symfony\Component\DependencyInjection\ContainerAware;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Symfony\Component\EventDispatcher\Event;

/**
 *
 * @category CCDNMessage
 * @package  MessageBundle
 *
 * @author   Reece Fowell <reece@codeconsortium.com>
 * @license  http://opensource.org/licenses/MIT MIT
 * @version  Release: 2.0
 * @link     https://github.com/codeconsortium/CCDNMessageMessageBundle
 *
 */
class BaseController extends ContainerAware
{
    /**
     *
     * @var \Symfony\Bundle\FrameworkBundle\Translation\Translator $translator
     */
    private $translator;

    /**
     *
     * @var \Symfony\Bundle\FrameworkBundle\Routing\Router $router
     */
    private $router;

    /**
     *
     * @var \Symfony\Bundle\TwigBundle\Debug\TimedTwigEngine $templating
     */
    private $templating;

    /**
     *
     * @var \Symfony\Component\HttpFoundation\Request $request
     */
    protected $request;

    /**
     *
     * @var \Symfony\Component\EventDispatcher\EventDispatcherInterface  $dispatcher;
     */
    protected $dispatcher;

    /**
     *
     * @var \Symfony\Component\Security\Core\SecurityContext $securityContext
     */
    private $securityContext;

    /**
     *
     * @var \CCDNMessage\MessageBundle\Model\FrontModel\FolderModel $folderModel
     */
    private $folderModel;

    /**
     *
     * @var \CCDNMessage\MessageBundle\Model\FrontModel\EnvelopeModel $envelopeModel
     */
    private $envelopeModel;

    /**
     *
     * @var \CCDNMessage\MessageBundle\Model\FrontModel\MessageModel $messageModel
     */
    private $messageModel;

    /**
     *
     * @var \CCDNMessage\MessageBundle\Model\FrontModel\ThreadModel $threadModel
     */
    private $threadModel;

    /**
     *
     * @var \CCDNMessage\MessageBundle\Model\FrontModel\RegistryModel $registryModel
     */
    private $registryModel;

    /**
     *
     * @access protected
     * @var \CCDNMessage\MessageBundle\Model\FrontModel\UserModel $userModel
     */
    protected $userModel;

    /**
     *
     * @var \CCDNMessage\MessageBundle\Component\FloodControl $floodControl;
     */
    private $floodControl;

    /**
     *
     * @access protected
     * @return \Symfony\Bundle\FrameworkBundle\Translation\Translator
     */
    protected function getTranslator()
    {
        if (null == $this->translator) {
            $this->translator = $this->container->get('translator');
        }

        return $this->translator;
    }

    /**
     *
     * @access protected
     * @param  string $message
     * @param  Array  $params
     * @param  string $bundle
     * @return string
     */
    protected function trans($message, $params = array(), $bundle = 'CCDNMessageMessageBundle')
    {
        return $this->getTranslator()->trans($message, $params, $bundle);
    }

    /**
     *
     * @access protected
     * @param  string $action, string $value
     * @return string
     */
    protected function setFlash($action, $value)
    {
        $this->container->get('session')->getFlashBag()->add($action, $value);
    }

    /**
     *
     * @access protected
     * @return \Symfony\Bundle\FrameworkBundle\Routing\Router
     */
    protected function getRouter()
    {
        if (null == $this->router) {
            $this->router = $this->container->get('router');
        }

        return $this->router;
    }

    /**
     *
     * @access protected
     * @param  string $route
     * @param  Array  $params
     * @return string
     */
    protected function path($route, $params = array())
    {
        return $this->getRouter()->generate($route, $params);
    }

    /**
     *
     * @access protected
     * @return \Symfony\Bundle\TwigBundle\Debug\TimedTwigEngine
     */
    protected function getTemplating()
    {
        if (null == $this->templating) {
            $this->templating = $this->container->get('templating');
        }

        return $this->templating;
    }

    /**
     *
     * @access protected
     * @return \Symfony\Component\HttpFoundation\Request
     */
    protected function getRequest()
    {
        if (null == $this->request) {
            $this->request = $this->container->get('request');
        }

        return $this->request;
    }

    /**
     *
     * @access protected
     * @param  string $prefix
     * @return Array
     */
    protected function getCheckedItemIds($prefix = 'check_', $enforceNumericType = true)
    {
        $request = $this->getRequest();

        $sanitarisedIds = array();

        if ($request->request->has($prefix)) {
            $itemIds = $request->request->get($prefix);

            foreach ($itemIds as $id => $val) {
                if ($enforceNumericType == true) {
                    if (! is_numeric($id)) {
                        continue;
                    }
                }

                $sanitarisedIds[] = $id;
            }
        }

        return $sanitarisedIds;
    }

    /**
     *
     * @access protected
     * @param  string $template
     * @param  Array  $params
     * @param  string $engine
     * @return string
     */
    protected function renderResponse($template, $params = array(), $engine = null)
    {
        return $this->getTemplating()->renderResponse($template . ($engine ?: $this->getEngine()), $params);
    }

    /**
     *
     * @access protected
     * @param  string                                             $url
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    protected function redirectResponse($url)
    {
        return new RedirectResponse($url);
    }

    /**
     *
     * @access protected
     * @return string
     */
    protected function getEngine()
    {
        return $this->container->getParameter('ccdn_message_message.template.engine');
    }

    /**
     *
     * @access protected
     * @return \Symfony\Component\Security\Core\SecurityContext
     */
    protected function getSecurityContext()
    {
        if (null == $this->securityContext) {
            $this->securityContext = $this->container->get('security.context');
        }

        return $this->securityContext;
    }

    /**
     *
     * @access protected
     * @return \Symfony\Component\Security\Core\User\UserInterface
     */
    protected function getUser()
    {
        return $this->getSecurityContext()->getToken()->getUser();
    }

    /**
     *
     * @access protected
     * @param  string $role
     * @return bool
     */
    protected function isGranted($role)
    {
        if (! $this->getSecurityContext()->isGranted($role)) {
            return false;
        }

        return true;
    }

    /**
     *
     * @access protected
     * @param  string                                                           $role|boolean $role
     * @throws \Symfony\Component\Security\Core\Exception\AccessDeniedException
     */
    protected function isAuthorised($role)
    {
        if (is_bool($role)) {
            if ($role == false) {
                throw new AccessDeniedException('You do not have permission to use this resource.');
            }

            return true;
        }

        if (! $this->isGranted($role)) {
            throw new AccessDeniedException('You do not have permission to use this resource.');
        }

        return true;
    }

    /**
     *
     * @access protected
     * @param  \Object                                                      $item
     * @param  string                                                       $message
     * @return bool
     * @throws Symfony\Component\HttpKernel\Exception\NotFoundHttpException
     */
    protected function isFound($item, $message = null)
    {
        if (null == $item) {
            throw new NotFoundHttpException($message ?: 'Page you are looking for could not be found!');
        }

        return true;
    }

    /**
     *
     * @access protected
     * @return string
     */
    protected function getSubmitAction()
    {
        $request = $this->getRequest();

        if ($request->request->has('submit')) {
            $action = key($request->request->get('submit'));
        } else {
            $action = 'post';
        }

        return $action;
    }

    protected function getQuery($query, $default)
    {
        return $this->getRequest()->query->get($query, $default);
    }

    protected function dispatch($name, Event $event)
    {
        if (! $this->dispatcher) {
            $this->dispatcher = $this->container->get('event_dispatcher');
        }

        $this->dispatcher->dispatch($name, $event);
    }

    /**
     *
     * @access protected
     * @return \CCDNMessage\MessageBundle\Model\FrontModel\FolderModel
     */
    protected function getFolderModel()
    {
        if (null == $this->folderModel) {
            $this->folderModel = $this->container->get('ccdn_message_message.model.folder');
        }

        return $this->folderModel;
    }

    /**
     *
     * @access protected
     * @return \CCDNMessage\MessageBundle\Model\FrontModel\EnvelopeModel
     */
    protected function getEnvelopeModel()
    {
        if (null == $this->envelopeModel) {
            $this->envelopeModel = $this->container->get('ccdn_message_message.model.envelope');
        }

        return $this->envelopeModel;
    }

    /**
     *
     * @access protected
     * @return \CCDNMessage\MessageBundle\Model\FrontModel\MessageModel
     */

Resources/views/User/Message/Partial/item_message.html.twig
{%- spaceless -%}
	{%- set sender = envelope.getMessage.getSentFromUser -%}
	{%- set recipient = envelope.getSentToUser -%}

	<table class="table table-striped table-hover message" id="{{- envelope.id -}}">
		<tbody>
			<tr>
				<td class="right" style="width: 80px;">
					<b>
						{{- 'message.sent-from-label' |trans({}, 'CCDNMessageMessageBundle') -}}
					</b>
				</td>
				<td class="left">
					{{- sender.username -}}
				</td>
			</tr>
			{%- if envelope.getMessage.getSentFromUser -%}
				{%- if envelope.getMessage.getSentFromUser.getId == app.user.id -%}
					<tr>
						<td class="right" style="width: 80px;">
							<b>
								{{- 'message.send-to-label' |trans({}, 'CCDNMessageMessageBundle') -}}
							</b>
						</td>
						<td class="left" colspan="3">
							{{- envelope.getMessage.getSendTo |title -}}
						</td>
					</tr>
				{%- endif -%}
			{%- else -%}
				<tr>
					<td class="right" style="width: 80px;">
						<b>
							{{- 'message.send-to-label' |trans({}, 'CCDNMessageMessageBundle') -}}
						</b>
					</td>
					<td class="left" colspan="3">
						{{- envelope.getMessage.getSendTo |title -}}
					</td>
				</tr>
			{%- endif -%}
			<tr>
				<td class="right" style="width: 80px;">
					<b>
						{{- 'message.subject-label' |trans({}, 'CCDNMessageMessageBundle') -}}
					</b>
				</td>
				<td class="left" colspan="3">
					{{- envelope.getMessage.getSubject -}}
				</td>
			</tr>
			<tr>
				<td class="right" style="width: 80px;">
					<b>
						{{- 'message.sent-datetime-label' |trans({}, 'CCDNMessageMessageBundle') -}}
					</b>
				</td>
				<td class="left">
					{{- envelope.getSentDate |date(ccdn_message_message.message.show.sent_datetime_format) -}}
				</td>
			</tr>
			<tr>
				<td class="left" colspan="4" style="overflow: hidden; padding: 25px;">
					<article>
						{{- envelope.getMessage.getBody -}}
						<br>
					</article>
				</td>
			</tr>
		</tbody>
	</table>
{%- endspaceless -%}

Resources/views/User/Message/Partial/item_preview.html.twig
{%- spaceless -%}
	{%- set sender = app.user -%}

	<table class="table table-striped table-bordered table-hover table-no-vertical-borders message-preview">
		<tbody>
			<tr>
				<td class="right" style="width: 80px;">
					<b>{{- 'message.sent-from-label' |trans({}, 'CCDNMessageMessageBundle') -}}</b>
				</td>
				<td class="left">
					{{- sender.username -}}
				</td>
			</tr>
			<tr>
				<td class="right" style="width: 80px;">
					<b>{{- 'message.send-to-label' |trans({}, 'CCDNMessageMessageBundle') -}}</b>
				</td>
				<td class="left" colspan="3">
					{{- message.getSendto |title -}}
				</td>
			</tr>
			<tr>
				<td class="right" style="width: 80px;">
					<b>{{- 'message.subject-label' |trans({}, 'CCDNMessageMessageBundle') -}}</b>
				</td>
				<td class="left" colspan="3">
					{{- message.getSubject -}}
				</td>
			</tr>
			<tr>
				<td class="right" style="width: 80px;">
					<b>{{- 'message.sent-datetime-label' |trans({}, 'CCDNMessageMessageBundle') -}}</b>
				</td>
				<td class="left">
					{{- message.getCreatedDate |date(ccdn_message_message.message.show.sent_datetime_format) -}}
				</td>
			</tr>
			<tr>
				<td class="left" colspan="4" style="overflow: hidden; padding: 25px;">
					<article>
						{{- message.getBody -}}
						<br>
					</article>
				</td>
			</tr>
		</tbody>
	</table>
{%- endspaceless -%}

Resources/views/User/Message/Partial/message_actions.html.twig
{%- spaceless -%}

	<a class="btn btn-primary" href="{{- path('ccdn_message_message_user_mail_compose_reply', {'envelopeId': envelope.id }) -}}">
		{{- 'link.message.reply' |trans({}, 'CCDNMessageMessageBundle') -}}
	</a>

	<a class="btn btn-primary" href="{{- path('ccdn_message_message_user_mail_compose_forward', {'envelopeId': envelope.id }) -}}">
		{{- 'link.message.forward' |trans({}, 'CCDNMessageMessageBundle') -}}
	</a>

	<a class="btn btn-default" href="{{- path('ccdn_message_message_user_mail_mark_as_unread', {'envelopeId': envelope.id }) -}}">
		{{- 'link.message.mark_as_unread' |trans({}, 'CCDNMessageMessageBundle') -}}
	</a>

	<a class="btn btn-danger" href="{{- path('ccdn_message_message_user_mail_delete', {'envelopeId': envelope.id }) -}}">
		{{- 'link.message.delete' |trans({}, 'CCDNMessageMessageBundle') -}}
	</a>

{%- endspaceless -%}