Entity/Envelope.php
<?php

/*
 * This file is part of the CCDNMessage MessageBundle
 *
 * (c) CCDN (c) CodeConsortium <http://www.codeconsortium.com/>
 *
 * Available on github <http://www.github.com/codeconsortium/>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace CCDNMessage\MessageBundle\Entity;

use CCDNMessage\MessageBundle\Entity\Model\EnvelopeModel;

/**
 *
 * @category CCDNMessage
 * @package  MessageBundle
 *
 * @author   Reece Fowell <reece@codeconsortium.com>
 * @license  http://opensource.org/licenses/MIT MIT
 * @version  Release: 2.0
 * @link     https://github.com/codeconsortium/CCDNMessageMessageBundle
 *
 */
class Envelope extends EnvelopeModel
{
    /**
     *
     * @var integer $id
     */
    protected $id;

    /**
     *
     * @var \DateTime $sentDate
     */
    protected $sentDate;

    /**
     *
     * @var Boolean $isDraft
     */
    protected $isDraft = false;

    /**
     *
     * @var Boolean $isRead
     */
    protected $isRead = false;

    /**
     *
     * @var Boolean $isFlagged
     */
    protected $isFlagged = false;

    /**
     *
     * @access public
     */
    public function __construct()
    {
        parent::__construct();
        // your own logic
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get sentDate
     *
     * @return datetime
     */
    public function getSentDate()
    {
        return $this->sentDate;
    }

    /**
     * Set sentDate
     *
     * @param  datetime $sentDate
     * @return Message
     */
    public function setSentDate($sentDate)
    {
        $this->sentDate = $sentDate;

        return $this;
    }

    /**
     * Get isDraft
     *
     * @return boolean
     */
    public function isDraft()
    {
        return $this->isDraft;
    }

    /**
     * Set isDraft
     *
     * @param  boolean $isDraft
     * @return Message
     */
    public function setDraft($isDraft)
    {
        $this->isDraft = $isDraft;

        return $this;
    }

    /**
     * Get isRead
     *
     * @return boolean
     */
    public function isRead()
    {
        return $this->isRead;
    }

    /**
     * Set isRead
     *
     * @param  boolean $isRead
     * @return Message
     */
    public function setRead($isRead)
    {
        $this->isRead = $isRead;

        return $this;
    }

    /**
     * Get isFlagged
     *
     * @return boolean
     */
    public function isFlagged()
    {
        return $this->isFlagged;
    }

    /**
     * Set isFlagged
     *
     * @param  boolean $isFlagged
     * @return Message
     */
    public function setFlagged($isFlagged)
    {
        $this->isFlagged = $isFlagged;

        return $this;
    }
}

Form/Type/User/MessageFormType.php
<?php

/*
 * This file is part of the CCDNMessage MessageBundle
 *
 * (c) CCDN (c) CodeConsortium <http://www.codeconsortium.com/>
 *
 * Available on github <http://www.github.com/codeconsortium/>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace CCDNMessage\MessageBundle\Form\Type\User;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

/**
 *
 * @category CCDNMessage
 * @package  MessageBundle
 *
 * @author   Reece Fowell <reece@codeconsortium.com>
 * @license  http://opensource.org/licenses/MIT MIT
 * @version  Release: 2.0
 * @link     https://github.com/codeconsortium/CCDNMessageMessageBundle
 *
 */
class MessageFormType extends AbstractType
{
    /**
     *
     * @access protected
     * @var string $messageClass
     */
    protected $messageClass;

    /**
     *
     * @access public
     * @var string $messageClass
     */
    public function __construct($messageClass)
    {
        $this->messageClass = $messageClass;
    }

    /**
     *
     * @access public
     * @param FormBuilder $builder, array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('send_to', 'text',
                array(
                    'data'               => $options['send_to'],
                    'label'              => 'form.label.to',
                    'translation_domain' => 'CCDNMessageMessageBundle',
                )
            )
            ->add('subject', 'text',
                array(
                    'data'               => $options['subject'],
                    'label'              => 'form.label.subject',
                    'translation_domain' => 'CCDNMessageMessageBundle',
                )
            )
            ->add('body', 'textarea',
                array(
                    'data'               => $options['body'],
                    'label'              => 'form.label.body',
                    'translation_domain' => 'CCDNMessageMessageBundle',
                )
            )
            ->add('is_flagged', 'checkbox',
                array(
                    'required'           => false,
                    'mapped'             => false,
                    'label'              => 'form.label.flagged',
                    'translation_domain' => 'CCDNMessageMessageBundle',
                )
            )
        ;
    }

    /**
     *
     * @access public
     * @param \Symfony\Component\OptionsResolver\OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class'         => $this->messageClass,
            'csrf_protection'    => true,
            'csrf_field_name'    => '_token',
            // a unique key to help generate the secret token
            'intention'          => 'message_item',
            'validation_groups'  => array('message_send'),
            'send_to'            => '',
            'subject'            => '',
            'body'               => '',
        ));
    }

    /**
     *
     * @access public
     * @return string
     */
    public function getName()
    {
        return 'Message';
    }
}

Resources/views/Common/Layout/Sidebar/sidebar.html.twig
{%- spaceless -%}

	<ul class="nav nav-pills nav-stacked">

		{%- set route = app.request.attributes.get('_route') -%}

		{%- if current_folder.name is not defined -%}
			{%- if envelope is defined -%}
				{%- set current_folder = envelope.getFolder -%}
			{%- endif -%}
		{%- endif -%}

		{%- if
			route == 'ccdn_message_message_user_mail_compose' or
			route == 'ccdn_message_message_user_mail_compose_to' or
			route == 'ccdn_message_message_user_mail_compose_reply' or
			route == 'ccdn_message_message_user_mail_compose_forward'
		-%}
			<li class="active">
				<a href="{{- path('ccdn_message_message_user_mail_compose') -}}">
					<i class="glyphicon glyphicon-pencil"></i>
					{{- 'link.message.compose' | trans({}, 'CCDNMessageMessageBundle') -}}
				</a>
			</li>
		{%- else -%}
			<li>
				<a href="{{- path('ccdn_message_message_user_mail_compose') -}}">
					<i class="glyphicon glyphicon-pencil"></i>
					{{- 'link.message.compose' | trans({}, 'CCDNMessageMessageBundle') -}}
				</a>
			</li>
		{%- endif -%}

		{%- set folders = message_bundle_folder_list() -%}

		{%- if folders['folders'] is defined -%}
			{%- import 'CCDNMessageMessageBundle:Common:Layout/Sidebar/sidebarMacro.html.twig' as format -%}

			{%- for folder in folders['folders'] -%}
				{%- if current_folder is defined
					and route != 'ccdn_message_message_user_mail_compose'
					and route != 'ccdn_message_message_user_mail_compose_to'
					and route != 'ccdn_message_message_user_mail_compose_reply'
					and route != 'ccdn_message_message_user_mail_compose_forward'
				-%}
					{{- format.folderWithCurrentFolder(folder, current_folder) -}}
				{%- else -%}
					{{- format.folder(folder) -}}
				{%- endif -%}
			{%- endfor -%}
		{%- endif -%}

		{#
		{% if folders['quota'] is defined -%}
			<li class="divider"></li>
			<li style="text-align:center;padding:5px;">
				<div class="col-md-3">
					<i class="glyphicon glyphicon-hdd"></i>
					{{- folders['quota']['allowed'] -}}&#37;&nbsp;
				</div>
				<div class="col-md-9">
					<div class="progress progress-danger">
						<div class="bar" style="width:{{- folders['quota']['used'] -}}%;"></div>
					</div>
				</div>
			</li>
		{%- endif -%}
		#}

	</ul>

{%- endspaceless -%}

Resources/views/Common/Layout/Sidebar/sidebarMacro.html.twig
{%- spaceless -%}
	{%- macro folder(folder) -%}
		<li	{%- if folder.getCachedUnreadCount %} class="marked_unread"{%- endif -%}>
			<a href="{{- path('ccdn_message_message_user_folder_show', {'folderName': folder.getName }) -}}">
				{%- if folder.getCachedUnreadCount %}
					<span class="badge pull-right">{{- folder.getCachedUnreadCount -}}</span>
				{%- endif -%}


				{%- if folder.name == 'inbox' or folder.name == 'sent' -%}
					{%- set icon = "-inbox" -%}
					{%- set folder_trans = 'title.folder.inbox' -%}
				{%- else -%}
					{%- if folder.name == 'drafts' -%}
						{%- set icon = "-share-alt" -%}
						{%- set folder_trans = 'title.folder.draft' -%}
					{%- else -%}
						{%- if folder.name == 'trash' -%}
							{%- set icon = "-trash" -%}
							{%- set folder_trans = 'title.folder.trash' -%}
						{%- else -%}
							{%- set icon = "-folder-close" -%}
							{%- set folder_trans = 'title.folder.current' -%}
						{%- endif -%}
					{%- endif -%}
				{%- endif -%}

				<i class="glyphicon glyphicon{{- icon -}}"></i>

				{{- folder_trans|title| trans({}, 'CCDNMessageMessageBundle') -}}
			</a>
		</li>
	{%- endmacro -%}

	{%- macro folderWithCurrentFolder(folder, current_folder) -%}
		<li
			{%- if current_folder is defined -%}
				{%- if folder.name == current_folder.name or folder.getCachedUnreadCount %} class="
						{%- if folder.name == current_folder.name -%}active {% endif -%}
						{%- if folder.getCachedUnreadCount -%}marked_unread{%- endif -%}
					"{%- endif -%}
			{%- else -%}
				{%- if folder.getCachedUnreadCount -%}
					class="{%- if folder.getCachedUnreadCount -%}marked_unread{%- endif -%}"
				{%- endif -%}
			{%- endif -%}
		>
			<a href="{{- path('ccdn_message_message_user_folder_show', {'folderName': folder.getName }) -}}">
				{%- if folder.getCachedUnreadCount %}
					<span class="badge pull-right">{{- folder.getCachedUnreadCount -}}</span>
				{%- endif -%}


				{%- if folder.name == 'inbox' or folder.name == 'sent' -%}
					{%- set icon = "-inbox" -%}
					{%- set folder_trans = 'title.folder.inbox' -%}
				{%- else -%}
					{%- if folder.name == 'drafts' -%}
						{%- set icon = "-share-alt" -%}
						{%- set folder_trans = 'title.folder.draft' -%}
					{%- else -%}
						{%- if folder.name == 'trash' -%}
							{%- set icon = "-trash" -%}
							{%- set folder_trans = 'title.folder.trash' -%}
						{%- else -%}
							{%- set icon = "-folder-close" -%}
							{%- set folder_trans = 'title.folder.current' -%}
						{%- endif -%}
					{%- endif -%}
				{%- endif -%}

				<i class="glyphicon glyphicon{{- icon -}}"></i>

				{{- folder_trans|title| trans({}, 'CCDNMessageMessageBundle') -}}
			</a>
		</li>
	{%- endmacro -%}

{%- endspaceless -%}